import { Beer } from './models/beer';

export const Beers: Beer[] = [{
    id: 1,
    name: 'Toma',
    country: 'Barrable',
    brewery: 'tbarrable0@eventbrite.com',
    type: 'Female',
    picture: 'http://dummyimage.com/115x182.png/dddddd/000000'
  }, {
    id: 2,
    name: 'Codie',
    country: 'Melesk',
    brewery: 'cmelesk1@linkedin.com',
    type: 'Male',
    picture: 'http://dummyimage.com/176x186.png/ff4444/ffffff'
  }, {
    id: 3,
    name: 'Loralyn',
    country: 'Duncklee',
    brewery: 'lduncklee2@who.int',
    type: 'Female',
    picture: 'http://dummyimage.com/232x116.bmp/ff4444/ffffff'
  }, {
    id: 4,
    name: 'Brander',
    country: 'Rowsel',
    brewery: 'browsel3@alexa.com',
    type: 'Male',
    picture: 'http://dummyimage.com/119x203.png/cc0000/ffffff'
  }, {
    id: 5,
    name: 'Luce',
    country: 'Waldera',
    brewery: 'lwaldera4@a8.net',
    type: 'Female',
    picture: 'http://dummyimage.com/116x244.bmp/dddddd/000000'
  }, {
    id: 6,
    name: 'Kippie',
    country: 'Brewood',
    brewery: 'kbrewood5@zimbio.com',
    type: 'Male',
    picture: 'http://dummyimage.com/119x229.png/5fa2dd/ffffff'
  }, {
    id: 7,
    name: 'Teddy',
    country: 'Lyndon',
    brewery: 'tlyndon6@cam.ac.uk',
    type: 'Male',
    picture: 'http://dummyimage.com/242x189.png/5fa2dd/ffffff'
  }, {
    id: 8,
    name: 'Ted',
    country: 'Zavattieri',
    brewery: 'tzavattieri7@livejournal.com',
    type: 'Male',
    picture: 'http://dummyimage.com/222x122.bmp/cc0000/ffffff'
  }, {
    id: 9,
    name: 'Alverta',
    country: 'Reubens',
    brewery: 'areubens8@biglobe.ne.jp',
    type: 'Female',
    picture: 'http://dummyimage.com/231x167.bmp/cc0000/ffffff'
  }, {
    id: 10,
    name: 'Adara',
    country: 'Bendig',
    brewery: 'abendig9@de.vu',
    type: 'Female',
    picture: 'http://dummyimage.com/133x177.png/5fa2dd/ffffff'
  }];
